stages:
  make_dataset:
    desc: Download data from Kaggle, create data dictionary and summary dtable
    cmd: python3 src/data/make_dataset.py -c titanic -tr train.csv -te test.csv -o
      ./data/raw
    deps:
    - src/data/make_dataset.py
    params:
    - dtypes
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
    - reports/figures/data_dictionary.tex
    - reports/figures/table_one.tex
