stages:
  prepare_data:
    cmd: python3 src/data/make_dataset.py -o data/interim/ -tr data/raw/train.csv
      -te data/raw/test.csv -r True
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/make_dataset.py
    outs:
    - data/interim/label_encoding.yaml
    - data/interim/test_categorized.csv
    - data/interim/train_categorized.csv
  train_model:
    cmd: python3 src/models/train_model.py -o models/ -tr data/interim/train_categorized.csv
      -te data/interim/test_categorized.csv
    deps:
    - data/interim/test_categorized.csv
    - data/interim/train_categorized.csv
    - src/models/train_model.py
    params:
    - random_seed
    - test_size
    outs:
    - models/test_submission.csv
    metrics:
    - models/metrics.json
