stages:
  prepare_data:
    cmd: python3 src/data/make_dataset.py -o data/interim/ -tr data/raw/train.csv
      -te data/raw/test.csv -r True
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/make_dataset.py
    outs:
    - data/interim/label_encoding.yaml
    - data/interim/test_categorized.csv
    - data/interim/train_categorized.csv
