classifier: random_forest
drop_cols:
- Name
- Cabin
- Ticket
dtypes:
  Age: float
  Embarked: category
  Fare: float
  Parch: int
  Pclass: category
  Sex: category
  SibSp: int
  Survived: category
feature_eng:
  featurize: false
imputation:
  Age: 29.6991
  Fare: 32.2042
  method: mean
model_params:
  logistic_regression: null
  naive_bayes: null
  neural_network: null
  random_forest:
    criterion: entropy
    max_depth: 20
    min_samples_leaf: 3
    min_samples_split: 9
  support_vector_machine: null
normalize: null
param_tuning:
  logistic_regression: null
  naive_bayes: null
  neural_network: null
  num_eval: 1000
  random_forest:
    criterion: entropy
    max_depth: 20
    min_samples_leaf: 3
    min_samples_split: 9
  scoring: roc_auc
  support_vector_machine: null
random_seed: 12345
train_test_split:
  n_split: 10
  shuffle: true
  target_class: Survived
predict:
  js_estimator: true
